export const TABLE_DATA = {
  data: [
    {
      id: 1,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 2,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 3,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 4,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 5,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 6,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 7,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 8,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 9,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 10,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 11,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 12,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 13,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 14,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
    {
      id: 15,
      img: `https://res.cloudinary.com/kingsleysolomon/image/upload/v1643440809/clapmi/avatar_3_lnfwyk.png`,
      firstName: 'Beetlejuice',
      lastName: 'juice',
      email: `example@gmail.com`,
      assignment: `fundamentals of Design patterns`,
      view: `view`,
    },
  ],
}
