// GLOBAL
export { default as Loading } from './global/Loading'
export { default as Button } from './global/Button'
export { default as SectionTwoCard } from './global/cards/SectionTwoCard'
export { default as Profile } from './global/profile/Profile'
export { default as TestimonialBanner } from './global/banners/TestimonialBanner'
export { default as ShortStepper } from './global/steppers/ShortStepper'
export { default as BannerII } from './global/banners/BannerII'
export { default as AboutSectionThreeCard } from './global/cards/AboutSectionThreeCard'
export { default as TeamCard } from './global/cards/teamCard/TeamCard'
export { default as SearchForm } from './global/forms/SearchForm'
export { default as SingleBlogCard } from './global/cards/blogCard/singleBlogCard/SingleBlogCard'
export { default as ContactForm } from './global/forms/contactForm/ContactForm'
export { default as CourseCard } from './global/cards/courseCard/CourseCard'
export { default as IntroCard } from './global/cards/introCard/IntroCard'
export { default as SignupForm } from './global/forms/signupForm/SignupForm'
export { default as LoginForm } from './global/forms/loginForm/LoginForm'
export { default as Payment } from './payment/Payment'
export { default as Accounts } from './payment/Accounts'
export { default as EmployerForm } from './global/forms/employerForm/EmployerForm'
export { default as HowItWorksCard } from './global/cards/employersCard/HowItWorksCard'
export { default as RoleCard } from './global/cards/employersCard/RoleCard'
export { default as DashboardBanner } from './global/banners/dashboardbanner/DashboardBanner'
export { default as AvatarStack } from './global/avatarStacks/AvatarStack'
export { default as CalendarApp } from './global/calendar/CalendarApp'
export { default as CalendarOffCanvas } from './global/offCanvas/CalendarOffCanvas'
export { default as Avatar } from './global/avatar/Avatar'
export { default as RelatedVideoCard } from './global/cards/relatedVideoCard/RelatedVideoCard'
export { default as MessageCard } from './global/cards/messageCard/MessageCard'
export { default as ScheduleClassForm } from './global/forms/scheduleClassFom/ScheduleClassForm'
export { default as StartAClass } from './global/modals/StartAClass'
export { default as OffCanvas } from './global/offCanvas/OffCanvas'
export { default as ClassDetails } from './global/cards/classDetails/ClassDetails'
export { default as JobRequirementModal } from './global/forms/jobRequirement/JobRequirementModal'
export { default as JobRequirementForm } from './global/forms/jobRequirement/jobRequirmentForm/JobRequirementForm'
export { default as AddAFile } from './global/modals/AddAFile'
export { default as Portal } from './global/POTAL/Portal'
export { default as AssignmentOffcanvas } from './global/offCanvas/AssignmentOffcanvas'
export { default as AddAClassOffcanvas } from './global/offCanvas/AddAClassOffcanvas'
export { default as AvatarDropdown } from './global/avatar/avatarDropdown/AvatarDropdown'
export { default as AdminSignupForm } from './global/forms/adminSignupForm/AdminSignupForm'
export { default as StudentSignupForm } from './global/forms/studentSignupForm/StudentSignupForm'
export { default as Feedback } from './global/modals/Feedback'
export { default as ToastComponent } from './global/toast/ToastComponent'

// HOME
export { default as Hero } from './home/hero'
export { default as SectionTwo } from './home/sectionTwo'
export { default as SectionThree } from './home/sectionThree'
export { default as SectionFour } from './home/sectionFour'
export { default as SectionFive } from './home/sectionFive'
export { default as SectionSix } from './home/sectionSix'

// ABOUT
export { default as AboutHero } from './aboutUs/hero'
export { default as AboutSectionTwo } from './aboutUs/sectionTwo'
export { default as AboutSectionThree } from './aboutUs/sectionThree'
export { default as AboutSectionFour } from './aboutUs/sectionFour'

// BLOG
export { default as BlogHero } from './blog/hero/BlogHero'
export { default as BlogSectionTwo } from './blog/sectionTwo'
export { default as BlogSectionThree } from './blog/sectionThree'
export { default as Header } from './blog/singleBlogPage/header/Header'
export { default as SingleBlogSectionThree } from './blog/singleBlogPage/sectionThree/SingleBlogSectionThree'

//CONTACT
export { default as ContactHero } from './contactUs/hero/ContactHero'
export { default as ContactSectionTwo } from './contactUs/sectionTwo/ContactSectionTwo'

//COURSES
export { default as CourseHero } from './course/courseHero'
export { default as CourseSectionTwo } from './course/sectionTwo/CourseSectionTwo'
export { default as CourseSectionFour } from './course/sectionFour/CourseSectionFour'

// intro
export { default as IntroHeader } from './intro/introHeader/IntroHeader'
export { default as IntroBody } from './intro/introBody/IntroBody'

// EMPLOYERS
export { default as EmployersHero } from './employers/hero'
export { default as EmployersSectionTwo } from './employers/sectionTwo'
export { default as EmployersSectionFour } from './employers/sectionFour'

// DASHBOARD
export { default as DashboardNavbar } from './dashboard/dashboardNavbar/DashboardNavbar'
export { default as DashboardMiniCard } from './dashboard/dashboardMiniCard/DashboardMiniCard'
export { default as DashboardResource } from './dashboard/resources/DashboardResource'
export { default as FeedbackCard } from './dashboard/dashboardStatFeedback/feedbacks/FeedbackCard'
export { default as GraphCard } from './dashboard/dashboardStatFeedback/stats/GraphCard'
export { default as ClassesTab } from './dashboard/tab/classesTab/ClassesTab'
export { default as ChatDisplay } from './dashboard/videoChatDisplay/ChatDisplay'
